# Generated by Django 5.0.3 on 2024-11-08 13:47

import fileupload.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(storage=fileupload.storage_backends.UthoCloudStorage, upload_to='media/'),
        ),
    ]
